### ISSUE TITLE
Command to install this on server

### ISSUE THREAD

**Issue by triptisbinnovations** [dzava/lighthouse-php#1]
Hello

I did not find any command to install this library on the server. Can you please suggest.

**Comment by dzava** [comment]
Add the following to your composer.json and run `composer require`.

```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dzava/lighthouse-php"
        }
    ],
    "require": {
        "dzava/lighthouse": "dev-master",
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Install Google Lighthouse `yarn add lighthouse`.

```
use Dzava\Lighthouse;

(new Lighthouse())
    ->setLighthousePath('./node_modules/lighthouse/lighthouse-cli/index.js')
    ->audit('http://example.com');
```

**Comment by triptisbinnovations** [comment]
Thanks for your response!

But I am unable to install this. This is displaying PHP version issue but my PHP version is 7.1. Please check the link for the screenshot http://prntscr.com/kqureq, http://prntscr.com/kqurw3.

I am using Plesk l7.1 server.  I don't know where i am going wrong. But when i have run php-cgi --version command, it is showing me 5.4.16 version but i have changed my php version to 7.1 everywhere.

Have you any idea?

**Comment by triptisbinnovations** [comment]
I have installed the library with some modifications.

My composer.json code is mentioned below

{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dzava/lighthouse-php"
        }
    ],
    "require": {
        "dzava/lighthouse": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "platform": {
            "php": "7.1.3"
        }
    }
}


And my php code is mentione below: 
include '../../../../../../root/vendor/autoload.php';
include '../../../../../../root/vendor/dzava/lighthouse/src/Lighthouse.php';
include '../../../../../../root/vendor/dzava/lighthouse/tests/Unit/LighthouseTest.php';
include '../../../../../../root/vendor/dzava/lighthouse/src/Lighthouse.php';
 use Dzava\Lighthouse; 

(new Lighthouse())
    ->setOutput('report.json')
    ->accessibility()
    ->bestPractices()
    ->performance()
    ->pwa()
    ->seo()
    ->audit('http://example.com');

When i run my php file. I am getting "Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /root/vendor/dzava/lighthouse/tests/Unit/LighthouseTest.php on line 8" error. Can you please suggest what i have missed in your library.

Thank you in Advance!

**Comment by dzava** [comment]
You only need to include the `autoload` file.

```
require '../../../../../../root/vendor/autoload.php';

use Dzava\Lighthouse;

(new Lighthouse())
    ->setOutput('report.json')
    ->accessibility()
    ->bestPractices()
    ->performance()
    ->pwa()
    ->seo()
    ->audit('http://example.com');
```

**Comment by triptisbinnovations** [comment]
Yes, i have tried the same. I am getting the "Fatal error: Uncaught Error: Class 'Dzava\Lighthouse' not found" issue.

My php code is mentioned below:

include '../../../../../../root/vendor/autoload.php';
 use Dzava\Lighthouse; 

(new Lighthouse())
    ->setOutput('report.json')
    ->accessibility()
    ->bestPractices()
    ->performance()
    ->pwa()
    ->seo()
    ->audit('http://example.com');

Can you please suggest me where I am going wrong.

**Comment by dzava** [comment]
Change the use statement to `use Dzava\Lighthouse\Lighthouse;`

```php
require '../../../../../../root/vendor/autoload.php';

use Dzava\Lighthouse\Lighthouse;

(new Lighthouse())
    ->setOutput('report.json')
    ->accessibility()
    ->bestPractices()
    ->performance()
    ->pwa()
    ->seo()
    ->audit('http://example.com');
```

**Comment by triptisbinnovations** [comment]
I am getting the fatal error in the audit. 

Fatal error: Uncaught Dzava\Lighthouse\Exceptions\AuditFailedException: Audit of 'http://www.google.com' failed in /root/vendor/dzava/lighthouse/src/Lighthouse.php:41 Stack trace: #0

**Comment by dzava** [comment]
Make sure lighthouse is installed globally or use the `setLighthousePath` method to specify the location of the script.

**Comment by triptisbinnovations** [comment]
I have checked your setLighthousePath function. 

setLighthousePath('./lighthouse.js')

But I have not found lighthouse.js in my lighthouse directory. I have installed the lighthouse library via yarn command and lighthouse folder created in my root directory. But there is no file related to lighthouse.js

**Comment by dzava** [comment]
It should be `node_modules/lighthouse/lighthouse-cli/index.js` inside the folder you ran the yarn command.

**Comment by dineshbips** [comment]
@dzava After doing all this when run page in php it open that js file in editor can you please suggest me on that what cause issues.
