### ISSUE TITLE
Installing lighthouse-php on a hostinger shared server?

### ISSUE THREAD

**Issue by dbee01** [dzava/lighthouse-php#10]
Trying to install this lib on hostinger for a web app i'm creating. 

When i run audit-fail.php on a subdomain I get ...

`/usr/bin/env: node: No such file or directory`

I tried doing a...

`ln -s /usr/bin/nodejs /usr/bin/node`

but on further reflection there doesn't appear to be any node in /usr/bin/ 

node isn't installed, npm isn't installed. Should i get on to the admins and ask them to install these packages?

**Comment by dzava** [comment]
Yes you need to have node installed.
