### ISSUE TITLE
Audit of 'http://example.com' failed

### ISSUE THREAD

**Issue by JesperKraght** [dzava/lighthouse-php#3]
Hi.

I'm having issues getting this to work in my Laravel Application.
I've done everything as requested:

1. Added the following to my composer.json.
```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/dzava/lighthouse-php"
        }
    ],
    "require": {
        "dzava/lighthouse": "dev-master",
    },
```
2. Installed the library using `composer require dzava/lighthouse`
3. Installed Google Lighthouse using `yarn add lighthouse`

But when I try to run it, I get an "Audit of 'DOMAIN-NAME' failed", no matter the URL.
I've also tried to use the `setLighthousePath`, but still the same.
```
    public function LightHouseScan($url) {
        return (new Lighthouse())
            ->setLighthousePath('../../node_modules/lighthouse/lighthouse-cli/index.js')
            ->setOutput('report.json')
            ->accessibility()
            ->bestPractices()
            ->performance()
            ->pwa()
            ->seo()
            ->audit($url);
    }
```

Any idea why this is happening?

**Comment by dzava** [comment]
Try this to see why it fails

```php
public function LightHouseScan($url) {
    try {
        return (new Lighthouse())
        ->setLighthousePath('../../node_modules/lighthouse/lighthouse-cli/index.js')
        ->setOutput('report.json')
        ->accessibility()
        ->bestPractices()
        ->performance()
        ->pwa()
        ->seo()
        ->audit($url);
    } catch(AuditFailedException $e) {
        dd($e->getOutput());
    }
}
```

**Comment by JesperKraght** [comment]
That outputs the exact same error message: Audit of 'http://example.com' failed

**Comment by AmityTek** [comment]
Got the same error ...
anyone can help us ?

Thanks

**Comment by dzava** [comment]
Check the value of `$exception->getOutput()` to see why it failed.

**Comment by AmityTek** [comment]
http://prntscr.com/w76fw4 and I don't how to solve this

**Comment by dzava** [comment]
Use the `setChromePath($path)` method to specify the location of the chrome binary.

**Comment by AmityTek** [comment]
Even if I specify the location itsn't working ... always the same error
