### ISSUE TITLE
Unable to install it in my laravel project

### ISSUE THREAD

**Issue by catchkomal** [dzava/lighthouse-php#5]
I am unable to install in my laravel project composer require dzava/lighthouse is not working for me

**Comment by victor-ponamariov** [comment]
Have the same issue :(

**Comment by catchkomal** [comment]
try to install in linux dedicated or VPS server it will work cause it
worked for me

**Comment by dzava** [comment]
Becuase this package is not published on packagist you have to add it as a repository in composer.json.

See https://github.com/dzava/lighthouse-php/issues/1#issuecomment-418441932 for details
