### ISSUE TITLE
Scan desktop or mobile or both

### ISSUE THREAD

**Issue by TimVividus** [dzava/lighthouse-php#7]
Using this tool, the scan defaults to mobile.  Is there a way to scan a desktop version of the site, or both mobile and desktop?  With the Lighthouse cli, you'd do something like _lighthouse https://website.com --preset=desktop_

**Comment by dzava** [comment]
See https://github.com/dzava/lighthouse-php/issues/6 for a quick way to run lightouse with the desktop preset.

For more control you could use a custom config, [here](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/config) you can find some examples.

I don't think that it is possible to run both audits at once.

**Comment by TimVividus** [comment]
Awesome, that's just what I was looking for :D  Thanks!
