### ISSUE TITLE
Unable to connect to Chrome

### ISSUE THREAD

**Issue by wkolcz-UMHS** [dzava/lighthouse-php#8]
I am trying this package to replace the node version I have running on the server. When I attempt to use test a url I am given a "Unable to connect to Chrome" with no other details. I am able to connect to chrome and run the tests in the node version so is there a way to get more details than this?

Also, do you have an example of the ./config.js you have in your example? Can it be added in PHP code rather than import a .js file?

Thanks!

**Comment by dzava** [comment]
Try using the `setChromePath` method and specify the absolute path to the chrome binary and make sure the user running the script has permissions to access and execute the binary.

[Here](https://github.com/GoogleChrome/lighthouse/blob/master/docs/configuration.md) you can read about the config file, and [here](https://github.com/GoogleChrome/lighthouse/tree/master/lighthouse-core/config) you can find examples. See the readme for an example on using an array to configure Lighthouse.
